# SPDX-FileCopyrightText: 2026 LibreCode coop and contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
version = 1
SPDX-PackageName = "pdf-signature-validator"
SPDX-PackageSupplier = "LibreCode <contact@librecode.coop>"
SPDX-PackageDownloadLocation = "https://github.com/LibreSign/pdf-signature-validator/"

default-license = "AGPL-3.0-or-later"
default-copyright = "2026 LibreCode coop and contributors"

[[annotations]]
path = [
    ".gitmodules",
    "README.md",
    "composer.json",
    "composer.lock",
    "deptrac.yaml",
    "tests/Fixtures/certs/self-signed-cert.pem",
    "tests/Fixtures/pdfs/real_jsignpdf_level1.pdf",
    "tests/Fixtures/pdfs/small_valid-signed.pdf",
    "tests/Fixtures/pdfs/small_valid.pdf",
    "vendor-bin/**/composer.json",
    "vendor-bin/**/composer.lock"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 LibreCode coop and contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ".github/workflows/reuse.yml"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Free Software Foundation Europe e.V. <https://fsfe.org>"
SPDX-License-Identifier = "CC0-1.0"
